
import { Translation, Employee, EmployeeStatus, Department } from './types';

export const TRANSLATIONS: Record<'en' | 'ar', Translation> = {
  en: {
    dashboard: "Dashboard",
    employees: "Employees",
    payroll: "Payroll",
    attendance: "Attendance",
    settings: "Settings",
    subscription: "Subscription",
    aiAssistant: "AI Assistant",
    totalEmployees: "Total Employees",
    pendingLeaves: "Pending Leaves",
    activeContracts: "Active Contracts",
    monthlyPayroll: "Monthly Payroll",
    search: "Search...",
    addEmployee: "Add Employee",
    name: "Name",
    position: "Position",
    department: "Department",
    status: "Status",
    action: "Action",
    trialMessage: "14 Days Free Trial Active",
    upgradeNow: "Upgrade to Pro",
    complianceMode: "Compliance Mode",
    ksa: "Saudi Arabia (KSA)",
    uae: "United Arab Emirates (UAE)",
    egypt: "Egypt",
    qatar: "Qatar",
    basicSalary: "Basic Salary",
    allowances: "Allowances",
    deductions: "Deductions",
    netSalary: "Net Salary",
    paymentMethod: "Payment Method",
    cash: "Cash",
    bank: "Bank",
    bankName: "Bank Name",
    accountNumber: "Account Number",
    export: "Export Payroll",
    employeeId: "Employee ID",
    email: "Email",
    phoneNumber: "Phone",
    nationalId: "National ID / Iqama",
    nationality: "Nationality",
    profilePicture: "Profile Picture",
    selectDepartment: "Select Department",
    clockIn: "Clock In",
    clockOut: "Clock Out",
    startBreak: "Start Break",
    endBreak: "End Break",
    leaveBalance: "Leave Balance",
    applyLeave: "Request Leave",
    myPortal: "My Portal",
    adminPanel: "Admin Panel",
    location: "Location",
    workingHours: "Working Hours",
    bonuses: "Bonuses",
    fixedAmount: "Fixed Amount",
    percentage: "Percentage",
    days: "Days",
    addAdjustment: "Add Adjustment",
    type: "Type",
    value: "Value",
    reason: "Reason",
    vacationDays: "Vacation Days",
    grossSalary: "Gross Salary",
    directManager: "Direct Manager",
    approve: "Approve",
    reject: "Reject",
    pending: "Pending",
    leaveType: "Leave Type",
    annual: "Annual",
    sick: "Sick",
    emergency: "Emergency",
    startDate: "Start Date",
    endDate: "End Date",
    salarySlip: "Salary Slip",
    payPeriod: "Pay Period",
    earnings: "Earnings",
    totalEarnings: "Total Earnings",
    totalDeductions: "Total Deductions",
    netPayable: "Net Payable",
    print: "Print",
    deductionReason: "Deduction Reason"
  },
  ar: {
    dashboard: "لوحة التحكم",
    employees: "الموظفين",
    payroll: "الرواتب",
    attendance: "الحضور",
    settings: "الإعدادات",
    subscription: "الاشتراك",
    aiAssistant: "مساعد الذكاء الاصطناعي",
    totalEmployees: "إجمالي الموظفين",
    pendingLeaves: "إجازات معلقة",
    activeContracts: "عقود سارية",
    monthlyPayroll: "رواتب الشهر",
    search: "بحث...",
    addEmployee: "إضافة موظف",
    name: "الاسم",
    position: "المنصب",
    department: "القسم",
    status: "الحالة",
    action: "الإجراء",
    trialMessage: "تجربة مجانية لمدة 14 يومًا",
    upgradeNow: "ترقية الباقة",
    complianceMode: "نظام الامتثال",
    ksa: "المملكة العربية السعودية",
    uae: "الإمارات العربية المتحدة",
    egypt: "مصر",
    qatar: "قطر",
    basicSalary: "الراتب الأساسي",
    allowances: "البدلات",
    deductions: "الخصومات",
    netSalary: "صافي الراتب",
    paymentMethod: "طريقة الدفع",
    cash: "كاش",
    bank: "تحويل بنكي",
    bankName: "اسم البنك",
    accountNumber: "رقم الحساب",
    export: "تصدير كشف الرواتب",
    employeeId: "رقم الموظف",
    email: "البريد الإلكتروني",
    phoneNumber: "رقم الهاتف",
    nationalId: "الرقم القومي / الإقامة",
    nationality: "الجنسية",
    profilePicture: "الصورة الشخصية",
    selectDepartment: "اختر الإدارة",
    clockIn: "تسجيل دخول",
    clockOut: "تسجيل خروج",
    startBreak: "بدء استراحة",
    endBreak: "إنهاء استراحة",
    leaveBalance: "رصيد الإجازات",
    applyLeave: "طلب إجازة",
    myPortal: "بوابتي",
    adminPanel: "لوحة الإدارة",
    location: "الموقع",
    workingHours: "ساعات العمل",
    bonuses: "المكافآت",
    fixedAmount: "مبلغ ثابت",
    percentage: "نسبة مئوية",
    days: "أيام",
    addAdjustment: "إضافة تسوية",
    type: "النوع",
    value: "القيمة",
    reason: "السبب",
    vacationDays: "أيام الإجازة",
    grossSalary: "إجمالي الراتب",
    directManager: "المدير المباشر",
    approve: "قبول",
    reject: "رفض",
    pending: "قيد الانتظار",
    leaveType: "نوع الإجازة",
    annual: "سنوية",
    sick: "مرضية",
    emergency: "اضطرارية",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    salarySlip: "مفردات مرتب",
    payPeriod: "فترة الدفع",
    earnings: "المستحقات",
    totalEarnings: "إجمالي المستحقات",
    totalDeductions: "إجمالي الاستقطاعات",
    netPayable: "صافي المستحق",
    print: "طباعة",
    deductionReason: "سبب الخصم"
  }
};

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'it', name: 'Information Technology', nameAr: 'تقنية المعلومات' },
  { id: 'hr', name: 'Human Resources', nameAr: 'الموارد البشرية' },
  { id: 'fin', name: 'Finance', nameAr: 'المالية' },
  { id: 'mkt', name: 'Marketing', nameAr: 'التسويق' },
  { id: 'ops', name: 'Operations', nameAr: 'العمليات' },
];

export const MOCK_EMPLOYEES: Employee[] = [
  { 
    id: 'admin_1', employeeId: 'EMP-0001', name: 'Super Admin', nameAr: 'المدير العام', 
    email: 'admin@maward.io', phoneNumber: '+966 50 000 0000',
    nationalId: '0000000000', nationality: 'System', nationalityAr: 'نظام',
    profilePicture: 'https://i.pravatar.cc/150?u=admin',
    position: 'CEO', positionAr: 'الرئيس التنفيذي', 
    department: 'Executive', departmentAr: 'الإدارة العليا', 
    basicSalary: 50000, allowances: 10000, deductions: 0,
    adjustments: [],
    joinDate: '2020-01-01', status: EmployeeStatus.Active,
    paymentMethod: 'Bank', bankName: 'Central Bank', accountNumber: 'CENTRAL001',
    leaveBalance: 30, totalLeaveEntitlement: 30
  },
  { 
    id: '1', employeeId: 'EMP-1021', name: 'Ahmed Ali', nameAr: 'أحمد علي', 
    email: 'ahmed.ali@maward.io', phoneNumber: '+966 50 123 4567',
    nationalId: '1029384756', nationality: 'Saudi', nationalityAr: 'سعودي',
    profilePicture: 'https://i.pravatar.cc/150?u=1',
    position: 'Software Engineer', positionAr: 'مهندس برمجيات', 
    department: 'Information Technology', departmentAr: 'تقنية المعلومات', 
    basicSalary: 12000, allowances: 3000, deductions: 250, deductionReason: 'Late Arrival',
    adjustments: [
      { id: 'adj1', category: 'Bonus', type: 'Days', value: 2, reason: 'Overtime Completion' }
    ],
    joinDate: '2022-01-15', status: EmployeeStatus.Active,
    paymentMethod: 'Bank', bankName: 'Al Rajhi Bank', accountNumber: 'SA12345678901234567890',
    leaveBalance: 21, totalLeaveEntitlement: 30,
    managerId: 'admin_1'
  },
  { 
    id: '2', employeeId: 'EMP-1022', name: 'Sara Mohamed', nameAr: 'سارة محمد', 
    email: 'sara.m@maward.io', phoneNumber: '+20 10 9876 5432',
    nationalId: '29012345678901', nationality: 'Egyptian', nationalityAr: 'مصرى',
    profilePicture: 'https://i.pravatar.cc/150?u=2',
    position: 'HR Manager', positionAr: 'مدير موارد بشرية', 
    department: 'Human Resources', departmentAr: 'الموارد البشرية', 
    basicSalary: 15000, allowances: 4000, deductions: 0,
    adjustments: [],
    joinDate: '2021-06-10', status: EmployeeStatus.Active,
    paymentMethod: 'Bank', bankName: 'National Bank of Egypt', accountNumber: 'EG98765432109876543210',
    leaveBalance: 12, totalLeaveEntitlement: 30,
    managerId: 'admin_1'
  },
  { 
    id: '3', employeeId: 'EMP-1023', name: 'Khalid Mansour', nameAr: 'خالد منصور', 
    email: 'khalid.m@maward.io', phoneNumber: '+971 50 555 1234',
    nationalId: '784-1985-1234567-1', nationality: 'Emirati', nationalityAr: 'إماراتي',
    profilePicture: 'https://i.pravatar.cc/150?u=3',
    position: 'Project Manager', positionAr: 'مدير مشاريع', 
    department: 'Operations', departmentAr: 'العمليات', 
    basicSalary: 18000, allowances: 5000, deductions: 100, deductionReason: 'Tool Damage',
    adjustments: [],
    joinDate: '2019-11-20', status: EmployeeStatus.Active,
    paymentMethod: 'Bank', bankName: 'Emirates NBD', accountNumber: 'AE12345678901234567890',
    leaveBalance: 4, totalLeaveEntitlement: 30,
    managerId: 'admin_1'
  },
  { 
    id: '4', employeeId: 'EMP-1024', name: 'Layla Hassan', nameAr: 'ليلى حسن', 
    email: 'layla.h@maward.io', phoneNumber: '+974 3333 4444',
    nationalId: '29212345678', nationality: 'Qatari', nationalityAr: 'قطري',
    profilePicture: 'https://i.pravatar.cc/150?u=4',
    position: 'Financial Analyst', positionAr: 'محلل مالي', 
    department: 'Finance', departmentAr: 'المالية', 
    basicSalary: 16000, allowances: 4000, deductions: 0,
    adjustments: [],
    joinDate: '2023-02-10', status: EmployeeStatus.OnLeave,
    paymentMethod: 'Bank', bankName: 'Qatar National Bank', accountNumber: 'QA12345678901234567890',
    leaveBalance: 28, totalLeaveEntitlement: 30,
    managerId: 'admin_1'
  }
];
